const popCultureUsernames = [
  // Movies
  "neo-trinity",
  "marty-mcfly",
  "tony-stark",
  "captain-vibranium",
  "dark-knight",
  "joker-chaos",
  "harley-quinnx",
  "vader-sith",
  "obiwan-force",
  "anakin-rises",
  "django-unchained",
  "max-furyroad",
  "john-wickk",
  "rocky-balboa",
  "creed-boxing",
  "indiana-relic",
  "bond-007x",
  "ethan-hunt",
  "jack-sparrowz",
  "doctor-strange",
  "deadpool-chaos",
  "logan-claws",
  "thor-thunder",
  "loki-trickster",
  "wanda-chaos",
  "panther-king",
  "spidey-verse",
  "venom-symbiote",
  "batfleck-dark",
  "superman-krypton",

  // Series
  "heisenberg-blue",
  "saul-goodman",
  "jesse-pinkman",
  "gus-fringg",
  "rick-sanchez",
  "morty-multiverse",
  "eleven-hawkins",
  "hopper-chief",
  "vecna-shadow",
  "jon-snoww",
  "night-kingx",
  "arya-stark",
  "khaleesi-dragon",
  "tyrion-wine",
  "peaky-blinder",
  "tommy-shelbyy",
  "arthur-chaos",
  "wednesday-addams",
  "dexter-blood",
  "lucifer-morning",
  "geralt-rivia",
  "yennefer-magic",
  "ciri-elderblood",
  "mandalorian-way",
  "grogu-force",
  "homelander-eye",
  "soldier-boyz",
  "starlight-vought",
  "omni-manvil",
  "invincible-mark",

  // Anime
  "goku-ultra",
  "vegeta-pride",
  "gojo-limitless",
  "sukuna-curse",
  "itachi-crow",
  "madara-uchiha",
  "naruto-shadow",
  "sasuke-revenge",
  "levi-ackerman",
  "eren-rumbling",
  "mikasa-blade",
  "light-yagami",
  "l-lawliet",
  "kaneki-ghoul",
  "zoro-santoryu",
  "luffy-gear5",
  "sanji-flames",
  "ace-firefist",
  "aizen-soul",
  "ichigo-bankai",

  // Musicians / Artists
  "weeknd-after",
  "drake-views",
  "kendrick-verse",
  "travis-utopia",
  "carti-vamps",
  "future-plutoo",
  "metro-boominx",
  "eminem-shady",
  "snoop-doggystyle",
  "kanye-dropout",
  "billie-neon",
  "dua-future",
  "rihanna-diamonds",
  "bruno-24k",
  "mj-moonwalk",
  "elvis-vibes",
  "freddie-mercuryx",
  "tupac-westside",
  "biggie-smallsz",
  "icecube-classic",

  // Rock Bands
  "nirvana-nevermind",
  "metallica-master",
  "slipknot-chaos",
  "linkin-hybrid",
  "green-dayx",
  "queen-bohemian",
  "acdc-thunder",
  "pinkfloyd-darkside",
  "radiohead-creep",
  "arctic-monkeyz",
  "beatles-revolver",
  "gunsnroses",
  "foo-fighters",
  "coldplay-parachute",
  "rammstein-fire",

  // Video Games
  "ghost-spartan",
  "kratos-rage",
  "atreus-arrow",
  "cj-grovestreet",
  "tommy-vercetti",
  "arthur-morgan",
  "john-marston",
  "trevor-chaotic",
  "cyberpunk-v",
  "geralt-witcher",
  "roach-rider",
  "master-chiefx",
  "doom-slayer",
  "mario-karted",
  "luigi-mansion",
  "zelda-hyrule",
  "link-master",
  "ganon-shadow",
  "pikachu-thunder",
  "ash-ketchum",
  "valorant-ace",
  "sage-revive",
  "jett-dash",
  "omen-shadow",
  "reyna-soul",
  "minecraft-creeper",
  "steve-blockcraft",
  "fortnite-builder",
  "elden-lord",
  "malenia-blade",

  // Comics / Misc
  "constantine-hell",
  "spawn-shadow",
  "hellboy-red",
  "silver-surfer",
  "galactus-hunger",
  "drdoom-mask",
  "rorschach-ink",
  "watchmen-vibe",
  "shrek-swamp",
  "kungfu-panda",
  "po-dragonwarrior",
  "toothless-night",
  "hiccup-rider",
  "ben10-omnitrix",
  "samurai-jackk",
  "avatar-aang",
  "zuko-firelord",
  "korra-spirit",
  "optimus-prime",
  "bumblebee-bot"
];

export function generateRandomUsername(): string {
  const option = popCultureUsernames[Math.floor(Math.random() * popCultureUsernames.length)];
  const suffix = Math.floor(100 + Math.random() * 900);
  return `${option}-${suffix}`;
}

export function generateRandomPassword(length = 16): string {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()-_";
  return Array.from({ length }, () => chars[Math.floor(Math.random() * chars.length)]).join("");
}
